'use client';
import Footer from '@/components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Navbar from '@/components/Navbar/Navbar';
import { SessionProvider } from 'next-auth/react';
import { usePathname } from 'next/navigation';
// import ScrollToTop from 'react-scroll-to-top';
// import { FaChevronUp } from 'react-icons/fa';


const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname =usePathname();

  return (
    <html lang="en">
      
      <body>
       
           <SessionProvider>
        <Navbar/>
        </SessionProvider>
        {children}
        </body>
    </html>
  );
}
